version: "3.9"

services:

  api:
    build: ./api
    container_name: api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env

  frontend:
    build: ./front
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    env_file:
      - ./front/.env
    depends_on:
      - api
      