FROM node:20-alpine AS build

WORKDIR /front
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# nginx para servir
FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /front/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]