FROM node:20-alpine

# diretório da aplicação
WORKDIR /api

# copiar dependências
COPY package*.json ./

# instalar dependências
RUN npm install

# copiar resto do projeto
COPY . .

# build do Nest (gera dist/)
RUN npm run build || npx tsc -p tsconfig.build.json --noEmitOnError false

RUN ls dist/ || (echo "AINDA FALHOU" && exit 1)

# expor porta padrão do Nest
EXPOSE 3000

# rodar versão buildada
CMD ["node", "dist/main"]
